
# ====================== Data Configs =========================

class: VisionSequenceModel

data:
  name: ToulouseRoadNetworkDataset
  class: StandardDataModule

  train_set:
    class: ToulouseRoadNetworkDataset
    params:
      sort_func: lex_sort
      img_file: archived/road_network_data/road/train_images.pickle
      label_file: archived/road_network_data/road/train.pickle
      train: True

  train_loader:
    class: torch.utils.data.DataLoader
    params:
      batch_size: 150     # effective batch size = batch_size * num_gpu
      num_workers: 8
      pin_memory: True
      shuffle: True
      collate_fn:
        class: PadSequenceConstant
        params:
          pad_value: -1.0

  val_set:
    class: ToulouseRoadNetworkDataset
    params:
      sort_func: lex_sort
      img_file: archived/road_network_data/road/valid_images.pickle
      label_file: archived/road_network_data/road/valid.pickle
      train: True

  val_loader:
    class: torch.utils.data.DataLoader
    params:
      batch_size: 150     # effective batch size = batch_size * num_gpu
      num_workers: 8
      pin_memory: True
      shuffle: False
      collate_fn:
        class: PadSequenceConstant
        params:
          pad_value: -1.0

# ==================== Training Configs =========================
training:
  save_dir: ./runs/road_network
  optimizer:
    class: torch.optim.AdamW
    params:
      lr: 0.0001
      weight_decay: 0.0000

  scheduler:
    class: torch.optim.lr_scheduler.OneCycleLR
    params:
      max_lr: 0.0001
      total_steps: 200            # should be the same as training epochs
      pct_start: 0.01
      div_factor: 25.0
      final_div_factor: 10000.0
      anneal_strategy: 'cos'

  params:                   # arguments for PyTorch Lightning Trainer
    max_epochs: 200         # should be the same as training epochs
    accelerator: gpu
    precision: 32
    strategy: ddp_find_unused_parameters_false
    enable_checkpointing: True
    check_val_every_n_epoch: 1
    log_every_n_steps: 50
    
  train_metrics:
    l1_loss: 
      class: nn.L1Loss
      weight: 0.0
    mse_loss:
      class: nn.MSELoss
      weight: 0.0
    ug_loss:
      class: UndirectedGraphLoss
      weight: 1.0

  eval_metrics:
    l1_loss: 
      class: nn.L1Loss
      weight: 0.0
    mse_loss:
      class: nn.MSELoss
      weight: 0.0
    ug_loss:
      class: UndirectedGraphLoss
      weight: 1.0

# ====================== Model Configs =========================

model:
  name: VisualGraphGPT
  class: vision_gpt
  params:
    in_chans: 1
    output_dim: 4
    emb_dim: 512
    img_size: 64
    gpt_name: gpt_small
    conv_backbone: efficientnet_b0
    pretrained: False
    stop_detector_cfg:
      model_name: StopTokenDetectorFloat
      stop_value: -1.0
      threshold: 0.8

  ema_model:
    class: ModelEmaV2
    params: 
      decay: 0.995